server:
  port: 8080
spring:
  application:
    name: server-springcloudgateway
  cloud:
    gateway:
      routes:
        - id: server-room
          uri: lb://SERVER-ROOM
          predicates:
            - Path=/r/**
          filters:
            - StripPrefix=1
        - id: server-everything-besides-room
          uri: lb://SERVER-GATEWAY
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0
#  security:
#    oauth2:
#      client:
#        accessTokenUri: http://localhost:7070/authserver/oauth/token
#        userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
#        clientId: authserver
#        clientSecret: passwordforauthserver
#      resource:
#        userInfoUri: http://localhost:9000/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

